development:
  adapter: postgresql
  encoding: unicode
  database: killer_queen_development
  pool: 5
  username: daytonn
  password:
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: killer_queen_test
  pool: 5
  username: daytonn
  password:
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: killer_queen
  pool: 5
  username: cooktabulous
  password: 8VQV3gfGW3NXrEew2888F2LBg32cYT
