default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: killer_queen_development
  pool: 5
  username: daytonn
  password:
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: killer_queen_test
  pool: 5
  username: daytonn
  password:
  min_messages: WARNING
